;             
CREATE USER IF NOT EXISTS SA SALT 'be2c343569f076af' HASH 'a1b7f58b1c29d153c6dc3440a92bb071e39667f8206cc0ae62bc1b74ac2d5d6f' ADMIN;           
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9AFC0D37_1F4B_42F0_B37C_52696979AB39 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ECC11397_1603_4A3B_A314_D2ED588FEF3A START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8B5FF4A3_3C95_4BF3_AE59_787C6BBE6426 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6BC29A16_6CE0_4BA0_A6FF_2F3AD4F82A63 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D1556E05_B269_4A4E_B266_2D379198A7CF START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7AF75200_065A_40E9_BB59_899B783FDD35 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_30A37DDF_1AD8_4221_A377_59B2AE0C12F3 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9B8865FF_32A6_4B36_9BE5_31EA65FB36BD START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0D8F1ECC_1ACD_476B_89B1_379B28B44C38 START WITH 1 BELONGS_TO_TABLE;    
CREATE CACHED TABLE PUBLIC.ADM_CONFIG(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D1556E05_B269_4A4E_B266_2D379198A7CF) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D1556E05_B269_4A4E_B266_2D379198A7CF,
    ENV_NAME VARCHAR(45) DEFAULT NULL,
    CONFIG_TYPE VARCHAR(45) DEFAULT NULL,
    USER_ID VARCHAR(45) DEFAULT NULL,
    PASSWORD VARCHAR(45) DEFAULT NULL,
    SEIBEL_SERVER VARCHAR(45) DEFAULT NULL,
    ROW_ID VARCHAR(45) DEFAULT NULL,
    LOG_FILE_PATH VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);         
ALTER TABLE PUBLIC.ADM_CONFIG ADD CONSTRAINT PUBLIC.CONSTRAINT_BF PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ADM_CONFIG;              
CREATE CACHED TABLE PUBLIC.LICENSE_MGT(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9AFC0D37_1F4B_42F0_B37C_52696979AB39) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9AFC0D37_1F4B_42F0_B37C_52696979AB39,
    TYPE VARCHAR(45) DEFAULT NULL,
    EXPIRY_DATE DATE NOT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);      
ALTER TABLE PUBLIC.LICENSE_MGT ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LICENSE_MGT;             
CREATE CACHED TABLE PUBLIC.ENV_INFO(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0D8F1ECC_1ACD_476B_89B1_379B28B44C38) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0D8F1ECC_1ACD_476B_89B1_379B28B44C38,
    NAME VARCHAR(45) DEFAULT NULL,
    HOST_NAME VARCHAR(45) DEFAULT NULL,
    ENTERPRISE_NAME VARCHAR(45) DEFAULT NULL,
    SERVER_HOST VARCHAR(45) DEFAULT NULL,
    SERVER_NAME VARCHAR(45) DEFAULT NULL,
    SERVICE VARCHAR(45) DEFAULT NULL,
    SEIBEL_PATH VARCHAR(45) DEFAULT NULL,
    ADM_PATH VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
); 
ALTER TABLE PUBLIC.ENV_INFO ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ENV_INFO;
CREATE CACHED TABLE PUBLIC.USERINFO(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6BC29A16_6CE0_4BA0_A6FF_2F3AD4F82A63) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6BC29A16_6CE0_4BA0_A6FF_2F3AD4F82A63,
    USERID VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) DEFAULT NULL,
    FIRST_NAME VARCHAR(45) DEFAULT NULL,
    LAST_NAME VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);
ALTER TABLE PUBLIC.USERINFO ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERINFO;
CREATE CACHED TABLE PUBLIC.AGENT_INFO(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8B5FF4A3_3C95_4BF3_AE59_787C6BBE6426) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8B5FF4A3_3C95_4BF3_AE59_787C6BBE6426,
    HOST VARCHAR(45) DEFAULT NULL,
    REMOTE_PORT VARCHAR(45) DEFAULT NULL,
    REMOTE_USER VARCHAR(45) DEFAULT NULL,
    REMOTE_ADDRESS VARCHAR(45) DEFAULT NULL,
    SERVER_NAME VARCHAR(45) DEFAULT NULL,
    SERVER_PORT VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);             
ALTER TABLE PUBLIC.AGENT_INFO ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.AGENT_INFO;              
CREATE CACHED TABLE PUBLIC.COMMANDTEMPLATES(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_ECC11397_1603_4A3B_A314_D2ED588FEF3A) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ECC11397_1603_4A3B_A314_D2ED588FEF3A,
    CODE VARCHAR(45) DEFAULT NULL,
    COMMAND VARCHAR(255) DEFAULT NULL,
    COMMAND_ORDER INT DEFAULT NULL,
    DESCRIPTION VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);         
ALTER TABLE PUBLIC.COMMANDTEMPLATES ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMMANDTEMPLATES;        
CREATE CACHED TABLE PUBLIC.EXPORT_REPOS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_7AF75200_065A_40E9_BB59_899B783FDD35) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7AF75200_065A_40E9_BB59_899B783FDD35,
    ENV_NAME VARCHAR(45) DEFAULT NULL,
    USER_ID VARCHAR(45) DEFAULT NULL,
    PASSWORD VARCHAR(45) DEFAULT NULL,
    ODBC VARCHAR(45) DEFAULT NULL,
    FILE_PATH VARCHAR(45) DEFAULT NULL,
    REPO_TYPE VARCHAR(45) DEFAULT NULL,
    LOG_FILE_PATH VARCHAR(45) DEFAULT NULL,
    REPO_NAME VARCHAR(45) DEFAULT NULL,
    TABLEDDLSYNC VARCHAR(45) DEFAULT NULL,
    INDEXDDLSYNC VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);              
ALTER TABLE PUBLIC.EXPORT_REPOS ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EXPORT_REPOS;            
CREATE CACHED TABLE PUBLIC.DEPLOYMENT_OPTIONS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_30A37DDF_1AD8_4221_A377_59B2AE0C12F3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_30A37DDF_1AD8_4221_A377_59B2AE0C12F3,
    CODE VARCHAR(45) DEFAULT NULL,
    DESCRIPTION VARCHAR(45) DEFAULT NULL,
    CATEGORY VARCHAR(45) DEFAULT NULL,
    COMMAND VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);     
ALTER TABLE PUBLIC.DEPLOYMENT_OPTIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_B2 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DEPLOYMENT_OPTIONS;      
CREATE CACHED TABLE PUBLIC.SERVER_INFO(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9B8865FF_32A6_4B36_9BE5_31EA65FB36BD) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9B8865FF_32A6_4B36_9BE5_31EA65FB36BD,
    SERVER_NAME VARCHAR(45) DEFAULT NULL,
    PORT_NUM INT DEFAULT NULL,
    URI VARCHAR(45) DEFAULT NULL,
    CONTEXT_ROOT VARCHAR(45) DEFAULT NULL
);          
ALTER TABLE PUBLIC.SERVER_INFO ADD CONSTRAINT PUBLIC.CONSTRAINT_54 PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SERVER_INFO;             
ALTER TABLE PUBLIC.USERINFO ADD CONSTRAINT PUBLIC.USERID_UNIQUE UNIQUE(USERID);               

INSERT INTO `deployment_options` VALUES (1,'StopServer','Stop Server','Option','sc $HOST_NAME Stop $SERVICE_NAME',NULL,NULL,NULL,NULL),(2,'CopySRFBS','Copy SRF/BS','Option',NULL,NULL,NULL,NULL,NULL),(3,'CopyWebTemplate','Copy Web Template','Option',NULL,NULL,NULL,NULL,NULL),(4,'CopyOtherFiles','Copy other Files (Specified in package)','Option',NULL,NULL,NULL,NULL,NULL),(5,'ImportRespository','Import Respository','Option',NULL,NULL,NULL,NULL,NULL),(6,'RenameRespository','Rename Respository','Option',NULL,NULL,NULL,NULL,NULL),(7,'ApplySchemaChanges','Apply Schema Changes','Option',NULL,NULL,NULL,NULL,NULL),(8,'StartServers','Start Servers','Option',NULL,NULL,NULL,NULL,NULL),(9,'ImportADM','Import  ADM','Option',NULL,NULL,NULL,NULL,NULL),(10,'BuildNow','Build Now','package',NULL,NULL,NULL,NULL,NULL),(11,'ScheduleDeploy','Schedule Deploy','package',NULL,NULL,NULL,NULL,NULL),(12,'MigrateSRFRepositoryNow','Migrate SRF/Repository Now','package',NULL,NULL,NULL,NULL,NULL),(13,'ADMExportImport','ADM Export/Import','package',NULL,NULL,NULL,NULL,NULL);
INSERT INTO COMMANDTEMPLATES (ID,CODE,COMMAND,command_order,CREATED_TIME, CREATED_USER ,UPDATED_TIME,UPDATED_USER ) VALUES (1,'BuildNow','C:\\Migration\\Auto-Build.bat',1,'2016-01-12',111,'2016-01-12', 111);
INSERT INTO `userinfo` VALUES (1,'dmtool','test1234','Punnam','Kolluru','2016-01-13 22:16:28','2016-01-13 22:16:28',0,0);
