CREATE USER IF NOT EXISTS SA SALT '04f8f8eb3eb0824f' HASH 'f2a17465083e5a03994a35fb74622c4ae91d1751096d83143e5c4cfee43fc8ca' ADMIN;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2978921E_582D_4F8D_9F8A_CAF0FC01CEF1 START WITH 14 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_09A19131_3EBC_410C_92E8_B846A68F6DE5 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_54010133_0689_46ED_A5A2_F9A140BE2D5D START WITH 16 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_03180B15_92C3_4F9F_A174_320D8DFFA4A7 START WITH 16 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C497EA1A_3E6B_498F_9837_59173BF7E56B START WITH 11 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F55F15CF_6C00_4E10_BE3B_17EDC87C6387 START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_81646375_057B_416C_9E8F_B327B6B5B6EA START WITH 6 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3B0B8D6C_4A5A_46CA_A293_7BFC3222B3FA START WITH 14 BELONGS_TO_TABLE;
CREATE CACHED TABLE PUBLIC.ENV_INFO(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_54010133_0689_46ED_A5A2_F9A140BE2D5D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_54010133_0689_46ED_A5A2_F9A140BE2D5D,
    NAME VARCHAR(45) DEFAULT NULL,
    HOST_NAME VARCHAR(45) DEFAULT NULL,
    ENTERPRISE_NAME VARCHAR(45) DEFAULT NULL,
    SERVER_HOST VARCHAR(45) DEFAULT NULL,
    SERVER_NAME VARCHAR(45) DEFAULT NULL,
    SERVICE VARCHAR(45) DEFAULT NULL,
    SEIBEL_PATH VARCHAR(45) DEFAULT NULL,
    ADM_PATH VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);
ALTER TABLE PUBLIC.ENV_INFO ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(ID);
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.ENV_INFO;
INSERT INTO PUBLIC.ENV_INFO(ID, NAME, HOST_NAME, ENTERPRISE_NAME, SERVER_HOST, SERVER_NAME, SERVICE, SEIBEL_PATH, ADM_PATH, CREATED_TIME, UPDATED_TIME, CREATED_USER, UPDATED_USER) VALUES
(5, 'QA-2-Punnam', 'lkjkj', 'kjk', 'kj', 'kjk', 'jkjk', 'jk', 'kjk', NULL, NULL, NULL, NULL),
(10, 'QA-12', 'lkjkj', 'kjk', 'kj', 'kjk', 'jkjk', 'jk', 'kjk', NULL, NULL, NULL, NULL),
(12, 'QA-12', 'SDSAD', 'SADSAD', 'sadSA', 'sadsa', 'sadSA', 'SDSA', 'DSADSA', NULL, NULL, NULL, NULL),
(13, 'QA-1', 'jhjh', 'jhj', 'hjhj', 'hjh', 'jhj', 'hjhj', 'hjh', NULL, TIMESTAMP '2015-11-16 11:51:44.0', NULL, 1111),
(14, 'QA-2', 'sdsad', 'sdasd', 'sdas', 'sdasds', 'dsadasd', 'dsadsad', 'dasdas', TIMESTAMP '2015-11-16 12:04:11.0', TIMESTAMP '2015-11-16 12:04:25.0', 0, 1111),
(15, 'H2DB-1', 'kjkj', 'kjk', 'jkj', 'kj', 'kjk', 'jk', 'jkj', TIMESTAMP '2015-11-20 14:27:58.0', TIMESTAMP '2015-11-20 14:27:58.0', 0, 0);
CREATE CACHED TABLE PUBLIC.USERINFO(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_03180B15_92C3_4F9F_A174_320D8DFFA4A7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_03180B15_92C3_4F9F_A174_320D8DFFA4A7,
    USERID VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) DEFAULT NULL,
    FIRST_NAME VARCHAR(45) DEFAULT NULL,
    LAST_NAME VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);
ALTER TABLE PUBLIC.USERINFO ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
-- 14 +/- SELECT COUNT(*) FROM PUBLIC.USERINFO;
INSERT INTO PUBLIC.USERINFO(ID, USERID, PASSWORD, FIRST_NAME, LAST_NAME, CREATED_TIME, UPDATED_TIME, CREATED_USER, UPDATED_USER) VALUES
(1, 'dmtool', 'test1234', NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'test1', 'test1234', 'John', 'Doe', NULL, NULL, NULL, NULL),
(3, 'test2', 'dsadsad', 'ddfdf', 'dsfdsf', NULL, NULL, NULL, NULL),
(4, 'test3', 'dsadsad', 'adds', 'sadsad', NULL, NULL, NULL, NULL),
(5, 'test4', 'dsadsad', 'fdgfgf', 'gfdgfdg', NULL, NULL, NULL, NULL),
(6, 'test5', 'dsadsad', 'dsfdsf', 'dsfdsf', NULL, NULL, NULL, NULL),
(7, 'test11', 'dsadsad', 'dsad', 'dsadsad', NULL, NULL, NULL, NULL),
(8, 'test12', 'dsadsad', 'vcxv', 'vcxvcx', NULL, NULL, NULL, NULL),
(9, 'test123', 'dsadsad', 'cx', 'cxvcx', NULL, NULL, NULL, NULL),
(10, 'test14', 'dsadsad', 'sds', 'sdsadsa', NULL, NULL, NULL, NULL),
(11, 'test21', 'dsadsad', 'xcxc', 'cxzcxz', NULL, NULL, NULL, NULL),
(13, 'test23', 'dsadsad', 'dsfds', 'dsadsa', NULL, NULL, NULL, NULL),
(14, 'test24', 'dsadsad', 'tytyt', 'hghg', NULL, NULL, NULL, NULL),
(15, 'test25', 'dsadsad', 'sdsd', 'dsadsa', NULL, NULL, NULL, NULL);
CREATE CACHED TABLE PUBLIC.ADM_CONFIG(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2978921E_582D_4F8D_9F8A_CAF0FC01CEF1) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2978921E_582D_4F8D_9F8A_CAF0FC01CEF1,
    ENV_NAME VARCHAR(45) DEFAULT NULL,
    CONFIG_TYPE VARCHAR(45) DEFAULT NULL,
    USER_ID VARCHAR(45) DEFAULT NULL,
    PASSWORD VARCHAR(45) DEFAULT NULL,
    SEIBEL_SERVER VARCHAR(45) DEFAULT NULL,
    ROW_ID VARCHAR(45) DEFAULT NULL,
    LOG_FILE_PATH VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);
ALTER TABLE PUBLIC.ADM_CONFIG ADD CONSTRAINT PUBLIC.CONSTRAINT_BF PRIMARY KEY(ID);
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.ADM_CONFIG;
INSERT INTO PUBLIC.ADM_CONFIG(ID, ENV_NAME, CONFIG_TYPE, USER_ID, PASSWORD, SEIBEL_SERVER, ROW_ID, LOG_FILE_PATH, CREATED_TIME, UPDATED_TIME, CREATED_USER, UPDATED_USER) VALUES
(6, 'QA-1', NULL, 'nmn', 'sads', 'fdsf', NULL, 'sadsa', NULL, NULL, NULL, NULL),
(7, 'Select Environment', NULL, 'user', 'password', 'seibel server', '', 'filepath', NULL, NULL, NULL, NULL),
(8, 'QA-2', 'Export', 'user id', 'password', 'seibelserver', NULL, 'logfile', NULL, NULL, NULL, NULL),
(9, 'QA-1', 'Export', 'nmn', 'sads', 'fdsf', NULL, 'sadsa', NULL, NULL, NULL, NULL),
(10, 'QA-2-Punnam', 'Import', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(11, 'QA-2-Punnam', 'Export', 'hghgjmm', 'jhjhmmm', 'jhjhjmmm', 'rowww', 'jhjhmmm', NULL, NULL, NULL, NULL),
(12, 'QA-2', 'Export', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13, 'QA-12', 'Export', 'fdsf', 'dfsdf', 'fsf', 'dsfs', 'dfsd', NULL, NULL, NULL, NULL);
CREATE CACHED TABLE PUBLIC.AGENT_INFO(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C497EA1A_3E6B_498F_9837_59173BF7E56B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C497EA1A_3E6B_498F_9837_59173BF7E56B,
    HOST VARCHAR(45) DEFAULT NULL,
    REMOTE_PORT VARCHAR(45) DEFAULT NULL,
    REMOTE_USER VARCHAR(45) DEFAULT NULL,
    REMOTE_ADDRESS VARCHAR(45) DEFAULT NULL,
    SERVER_NAME VARCHAR(45) DEFAULT NULL,
    SERVER_PORT VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);
ALTER TABLE PUBLIC.AGENT_INFO ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.AGENT_INFO;
INSERT INTO PUBLIC.AGENT_INFO(ID, HOST, REMOTE_PORT, REMOTE_USER, REMOTE_ADDRESS, SERVER_NAME, SERVER_PORT, CREATED_TIME, UPDATED_TIME, CREATED_USER, UPDATED_USER) VALUES
(1, NULL, '0', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
(2, NULL, '0', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
(3, NULL, '0', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
(4, NULL, '0', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL),
(5, '0:0:0:0:0:0:0:1', '63282', NULL, '0:0:0:0:0:0:0:1', 'localhost', '8080', NULL, NULL, NULL, NULL),
(6, '0:0:0:0:0:0:0:1', '63298', NULL, '0:0:0:0:0:0:0:1', 'localhost', '8080', NULL, NULL, NULL, NULL),
(7, '0:0:0:0:0:0:0:1', '53620', NULL, '0:0:0:0:0:0:0:1', 'localhost', '8080', NULL, NULL, NULL, NULL),
(8, '0:0:0:0:0:0:0:1', '53620', NULL, '0:0:0:0:0:0:0:1', 'localhost', '8080', NULL, NULL, NULL, NULL),
(9, '0:0:0:0:0:0:0:1', '54271', NULL, '0:0:0:0:0:0:0:1', 'localhost', '8080', NULL, NULL, NULL, NULL),
(10, '0:0:0:0:0:0:0:1', '54271', NULL, '0:0:0:0:0:0:0:1', 'localhost', '8080', NULL, NULL, NULL, NULL);
CREATE CACHED TABLE PUBLIC.COMMANDTEMPLATES(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F55F15CF_6C00_4E10_BE3B_17EDC87C6387) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F55F15CF_6C00_4E10_BE3B_17EDC87C6387,
    CODE VARCHAR(45) DEFAULT NULL,
    COMMAND VARCHAR(255) DEFAULT NULL,
    COMMAND_ORDER INT DEFAULT NULL,
    DESCRIPTION VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);
ALTER TABLE PUBLIC.COMMANDTEMPLATES ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.COMMANDTEMPLATES;
INSERT INTO PUBLIC.COMMANDTEMPLATES(ID, CODE, COMMAND, COMMAND_ORDER, DESCRIPTION, CREATED_TIME, UPDATED_TIME, CREATED_USER, UPDATED_USER) VALUES
(1, 'StopServer', 'sc //$HOST_NAME stop //$SERVICE_NAME', 1, 'Server', NULL, NULL, NULL, NULL);
CREATE CACHED TABLE PUBLIC.DEPLOYMENT_OPTIONS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_3B0B8D6C_4A5A_46CA_A293_7BFC3222B3FA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3B0B8D6C_4A5A_46CA_A293_7BFC3222B3FA,
    CODE VARCHAR(45) DEFAULT NULL,
    DESCRIPTION VARCHAR(45) DEFAULT NULL,
    CATEGORY VARCHAR(45) DEFAULT NULL,
    COMMAND VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);
ALTER TABLE PUBLIC.DEPLOYMENT_OPTIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_B2 PRIMARY KEY(ID);
-- 13 +/- SELECT COUNT(*) FROM PUBLIC.DEPLOYMENT_OPTIONS;
INSERT INTO PUBLIC.DEPLOYMENT_OPTIONS(ID, CODE, DESCRIPTION, CATEGORY, COMMAND, CREATED_TIME, UPDATED_TIME, CREATED_USER, UPDATED_USER) VALUES
(1, 'StopServer', 'Stop Server', 'Option', 'sc $HOST_NAME Stop $SERVICE_NAME', NULL, NULL, NULL, NULL),
(2, 'CopySRFBS', 'Copy SRF/BS', 'Option', NULL, NULL, NULL, NULL, NULL),
(3, 'CopyWebTemplate', 'Copy Web Template', 'Option', NULL, NULL, NULL, NULL, NULL),
(4, 'CopyOtherFiles', 'Copy other Files (Specified in package)', 'Option', NULL, NULL, NULL, NULL, NULL),
(5, 'ImportRespository', 'Import Respository', 'Option', NULL, NULL, NULL, NULL, NULL),
(6, 'RenameRespository', 'Rename Respository', 'Option', NULL, NULL, NULL, NULL, NULL),
(7, 'ApplySchemaChanges', 'Apply Schema Changes', 'Option', NULL, NULL, NULL, NULL, NULL),
(8, 'StartServers', 'Start Servers', 'Option', NULL, NULL, NULL, NULL, NULL),
(9, 'ImportADM', 'Import  ADM', 'Option', NULL, NULL, NULL, NULL, NULL),
(10, 'BuildNow', 'Build Now', 'package', NULL, NULL, NULL, NULL, NULL),
(11, 'ScheduleDeploy', 'Schedule Deploy', 'package', NULL, NULL, NULL, NULL, NULL),
(12, 'MigrateSRFRepositoryNow', 'Migrate SRF/Repository Now', 'package', NULL, NULL, NULL, NULL, NULL),
(13, 'ADMExportImport', 'ADM Export/Import', 'package', NULL, NULL, NULL, NULL, NULL);
CREATE CACHED TABLE PUBLIC.LICENSE_MGT(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_09A19131_3EBC_410C_92E8_B846A68F6DE5) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_09A19131_3EBC_410C_92E8_B846A68F6DE5,
    TYPE VARCHAR(45) DEFAULT NULL,
    EXPIRY_DATE DATE NOT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);
ALTER TABLE PUBLIC.LICENSE_MGT ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LICENSE_MGT;
CREATE CACHED TABLE PUBLIC.EXPORT_REPOS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_81646375_057B_416C_9E8F_B327B6B5B6EA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_81646375_057B_416C_9E8F_B327B6B5B6EA,
    ENV_NAME VARCHAR(45) DEFAULT NULL,
    USER_ID VARCHAR(45) DEFAULT NULL,
    PASSWORD VARCHAR(45) DEFAULT NULL,
    ODBC VARCHAR(45) DEFAULT NULL,
    FILE_PATH VARCHAR(45) DEFAULT NULL,
    REPO_TYPE VARCHAR(45) DEFAULT NULL,
    LOG_FILE_PATH VARCHAR(45) DEFAULT NULL,
    REPO_NAME VARCHAR(45) DEFAULT NULL,
    TABLEDDLSYNC VARCHAR(45) DEFAULT NULL,
    INDEXDDLSYNC VARCHAR(45) DEFAULT NULL,
    CREATED_TIME DATETIME DEFAULT NULL,
    UPDATED_TIME DATETIME DEFAULT NULL,
    CREATED_USER INT DEFAULT NULL,
    UPDATED_USER INT DEFAULT NULL
);
ALTER TABLE PUBLIC.EXPORT_REPOS ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.EXPORT_REPOS;
INSERT INTO PUBLIC.EXPORT_REPOS(ID, ENV_NAME, USER_ID, PASSWORD, ODBC, FILE_PATH, REPO_TYPE, LOG_FILE_PATH, REPO_NAME, TABLEDDLSYNC, INDEXDDLSYNC, CREATED_TIME, UPDATED_TIME, CREATED_USER, UPDATED_USER) VALUES
(1, 'QA-1', 'userid', 'password', 'server', 'e file path', 'Export', 'logfile', 'row', 'ddl sync', 'index', NULL, NULL, NULL, NULL),
(3, 'QA-2-Punnam', NULL, NULL, NULL, NULL, 'DDLSync', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(4, 'UdateQA-1m', NULL, NULL, NULL, NULL, 'Import', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, 'QA-12', 'dfdf', 'dfd', 'df', 'fsdf', 'Export', 'fdf', 'dfd', 'dfsd', 'dfsd', NULL, NULL, NULL, NULL);
ALTER TABLE PUBLIC.USERINFO ADD CONSTRAINT PUBLIC.USERID_UNIQUE UNIQUE(USERID);
